import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

import useApi from '../lib/use-api';

import { useUser } from '@auth0/nextjs-auth0';

type UserProfile = {
  firstName: string;
  lastName: string;
  emailAddress: string;
}

export default function Home() {

  let { user, error, isLoading } = useUser();
  let userDetails : UserProfile = { firstName: "", lastName: "", emailAddress: ""};

  console.log(JSON.stringify(user));
    console.log("about to hit the api");
    
    const { response, profileError, profileIsLoading } = useApi('/api/userprofile');

    console.log(`response: ${JSON.stringify(response)}`);

    userDetails = response;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        {(user && userDetails) ? 
          (
            <>
            <div>Welcome {user.name}! <Link href="/api/auth/logout">Logout</Link></div>
            <div>View your registrations: <Link href="/registrations">My registrations</Link></div>
            </>
          ) : <Link href="/api/auth/login">Login</Link>}
  
        <h1 className={styles.title}>
          Idam profile site
        </h1>
  
        {(user && userDetails) ?
  
          <div className={styles.grid}>
            <div className={styles.card}>
              <label>Firstname&nbsp;
                <input type="text" value={userDetails.firstName} />
              </label>            
            </div>
  
            <div className={styles.card}>
              <label>Lastname&nbsp;
                <input type="text" value={userDetails.lastName} />
              </label>            
            </div>
  
            <div className={styles.card}>
              <label>Email&nbsp;
                <input type="text" value={userDetails.emailAddress} />
              </label>            
            </div>
  
            <div className={styles.card}>            
                <button>Update</button>            
            </div>          
          </div>
  
        :
  
          <p className={styles.description}></p>
  
        }
  
        </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
